update dockerfile + docker compose support
tfkhdyt/wa-sticker-bot pull request #3
Opened 2023-01-26 06:36 UTC by AnonGhostID

kalo puppeteernya ga diinstal, chromenya gamau jalan didalem Docker bang

2023-01-26 11:19 UTC, tfkhdyt commented
Thanks, saya baru belajar Docker soalnya hehe

2023-01-26 11:21 UTC, tfkhdyt commented
Btw udah tested kah? Saya lagi males ngetes nya wkwkwk

2023-01-27 02:11 UTC, AnonGhostID commented
udah tested, di vm ubuntu gcp bang

2023-01-27 02:15 UTC, AnonGhostID commented
commit yg changedata gausa diacc bang wkwkwk penggunaan prbadi soalnya

2023-01-27 03:29 UTC, tfkhdyt approved these changes

2023-01-27 03:30 UTC, tfkhdyt requested changes
Yang ini harusnya gak perlu di-pull request

2023-01-27 03:31 UTC, merged